# Generated by Django 5.2.5 on 2025-08-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='branch',
            new_name='parent_id',
        ),
    ]
