# Generated by Django 5.2.5 on 2025-08-22 13:51

import graph.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_comment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=graph.models.kyiv_now),
        ),
    ]
