# Generated by Django 5.2.5 on 2025-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isGPT',
            field=models.BooleanField(default=False),
        ),
    ]
