# Generated by Django 5.2.5 on 2025-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('login', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
